# Polynomial

In [1]:
import torch
import numpy as np

In [2]:
x_input = torch.tensor(5.0, requires_grad=True)

In [3]:
def polynomial(x):
    return 3*x**2+2*x+1

In [4]:
y= polynomial(x_input)
print(y)

tensor(86., grad_fn=<AddBackward0>)


In [5]:
dy_dx=y.backward()
print(x_input.grad)

tensor(32.)


In [15]:
print(x_input.grad)

tensor(32.)


# Vector valued function

In [8]:
x_vector = torch.tensor([2.8,5.1], requires_grad=True)
print(x_vector)

tensor([2.8000, 5.1000], requires_grad=True)


In [15]:
# Defining a non trivial function which ouputs a torch.tensor
def vector_function(x):
    y1 = x[0]**2
    y2 = x[1]**x[0]
    y3 = torch.sin(x[1])*x[1]
    return torch.stack([y1,y2,y3])


y = vector_function(x_vector)
print(y)


tensor([ 7.8400, 95.7627, -4.7217], grad_fn=<StackBackward0>)


In [16]:
# Creating the vector v which is of the same size as y
v=torch.tensor([1.0,1.0,1.0])

# perform the backward pass
y.backward(v)

In [17]:
print(x_vector.grad)

tensor([161.6205,  53.5775])


# Differentiation of the parameters

In [18]:
def function_params(x,params):
    return params[0]*torch.sin(x)+params[1]**3

In [33]:
# Here I define parameters as torch.tensor which will be differentiated later on
params = torch.tensor([2.4,1.8], requires_grad=True)





# Let's see if the function is working
# Defining output which will be differentiated later
output1 = function_params(x_input, params)
print(output1)


tensor(3.5306, grad_fn=<AddBackward0>)


In [34]:
output1.backward()

In [35]:
print(f"This is the output of params.grad: {params.grad}")
print(f"This is the ouput of x_input.grad: {x_input.grad}")


This is the output of params.grad: tensor([-0.9589,  9.7200])
This is the ouput of x_input.grad: 34.72315979003906


In [36]:
# Similarly let me try the above where input is not differentaited
x_constant = torch.tensor(5.3, requires_grad=False)

output2 = function_params(x_constant, params)
# Now let me calculate the backward pass

output2.backward()




In [37]:
# Let's see the output in this case. It should show an error

print(f"This is the output of params.grad: {params.grad}")
print(f"This is the ouput of x_constant.grad: {x_constant.grad}")


This is the output of params.grad: tensor([-1.7912, 19.4400])
This is the ouput of x_constant.grad: None
